In [1]:
import numpy as np

In [2]:
#Basic Array Creation
arr = np.array([1,2,3,4])

array([1, 2, 3, 4])

In [7]:
a = [1,2,3,4.4]
a

[1, 2, 3, 4.4]

In [8]:
np.array(a)

array([1. , 2. , 3. , 4.4])

In [10]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr = np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [20]:
arr = np.zeros((6, 3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [22]:
arr = np.linspace(1,5,2)
arr

array([1., 5.])

In [23]:
arr = np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [25]:
arr = np.linspace(1,5,100)
arr

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [27]:
#Random Number Generation
np.random.rand(10)

array([0.87783505, 0.34608058, 0.55704101, 0.84174149, 0.53949276,
       0.66660547, 0.26792185, 0.16254574, 0.99093671, 0.5903909 ])

In [29]:
np.random.randn(10)

array([-2.17539268,  1.17580379, -0.61183642, -1.51122555,  1.02554399,
       -1.44825021, -0.4135992 , -0.27506535, -0.1237628 ,  0.53820508])

In [30]:
np.random.randint(6)

3

In [32]:
np.random.randint(10, 20, 10)

array([16, 15, 15, 10, 12, 19, 12, 19, 11, 18], dtype=int32)

In [36]:
#Array Attributes
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr.shape

(3, 3)

In [38]:
arr.size

9

In [39]:
arr.dtype

dtype('int64')

In [40]:
#Array Methods

In [41]:
arr.min()

np.int64(1)

In [42]:
arr.max()

np.int64(9)

In [43]:
arr.sum()

np.int64(45)

In [46]:
#Row Wise Sum axis = 0, axis = 1
np.sum(arr, axis=0)

array([12, 15, 18])

In [47]:
arr.mean()

np.float64(5.0)

In [48]:
arr.std()

np.float64(2.581988897471611)

In [49]:
#Max element index
arr.argmax()

np.int64(8)

In [50]:
arr.argmin()

np.int64(0)

In [53]:
#Reshaping and Resizing
arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [57]:
#6 x 5 = 30
#Resize
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])