In [1]:
 import numpy as np

In [3]:
#Numpy Indexing and Slicing of Vectors
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[1]

np.int64(12)

In [9]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

Numpy Indexing and Slicing of Matrix

In [10]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [11]:
arr[0]

array([1, 2, 3, 4, 5])

In [15]:
arr[0][3]

np.int64(4)

In [18]:
arr[0:2,1:3] 

array([[2, 3],
       [7, 8]])

In [20]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [26]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [31]:
#Boolean Index

In [32]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [38]:
bool_index = arr%2 == 0
bool_index

array([ True,  True,  True,  True,  True])

In [41]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])